# Copyright 2017 Holger Just
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE.txt file for details.

sudo: false
language: ruby
rvm:
  - 2.2.5
before_install: gem install bundler -v 1.12.5
