# Copyright 2017 - 2018 Holger Just
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE.txt file for details.

language: ruby
sudo: false
dist: trusty

cache: bundler

rvm:
  # Latest Rubies on top
  - 2.5.1
  - jruby-9.2.0.0

  # Older versions
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - jruby-9.1.17.0
  - jruby-9.0.5.0

  # HEAD-Rubies (might break)
  - ruby-head
  - jruby-head

matrix:
  include:
    - rvm: 2.5.1
      env: COVERAGE=1

    # An older Ruby/Rack combination as used by Rails 3.2. As long as it works
    # with our required Ruby version, we want to support it.
    - rvm: 2.1.10
      env: RACK_VERSION=1.4.5

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - "gem install bundler"

script:
  - bundle exec rspec
