# Copyright 2017 Holger Just
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE.txt file for details.

language: ruby
sudo: false
dist: trusty

cache: bundler

rvm:
  # Latest Rubies on top
  - 2.4.2
  - jruby-9.1.13.0

  # Older versions
  - 2.3.5
  - 2.2.8
  - 2.1.10
  - jruby-9.0.5.0

  # HEAD-Rubies (might break)
  - ruby-head
  - jruby-head

matrix:
  include:
    - rvm: 2.3.5
      env: COVERAGE=1

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - "gem install bundler"

script:
  - bundle exec rspec
