# Copyright 2017 Holger Just
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE.txt file for details.

language: ruby
sudo: false

cache: bundler

rvm:
  # Latest Rubies on top
  - 2.4.1
  - jruby-9.1.8.0

  # Older versions
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - jruby-9.0.5.0

  # HEAD-Rubies (might break)
  - ruby-head
  - jruby-head

jdk:
  - oraclejdk8

matrix:
  include:
    - rvm: 2.3.4
      jdk: oraclejdk8
      env: COVERAGE=1

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - "gem install bundler"

script:
  - bundle exec rspec
